version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3309"
    volumes:
      - book_devdojo_data:/var/lib/mysql

volumes:
  book_devdojo_data:
