server:
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?createDatabaseIfNotExist=true
    username: root
    password: kailan
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG